language: node_js
node_js:
    - "5.1.0"
script: node_modules/karma/bin/karma start tests/karma.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install